import type {
  CategoryMeta,
  Hook,
  HookCategory,
  HookGapSuggestion,
  HookPattern,
  InspirationVideo,
  Intent,
  MediaHookMatch,
  PatternMeta,
  ProductionTier,
  VerticalExample,
  VerticalProfile,
} from "./types";

export const patternMeta: Record<HookPattern, PatternMeta> = {
  Interrupt: {
    key: "Interrupt",
    description: "Breaks the expected feed rhythm with a hard visual, audio, or text change.",
    color: "#ef5d65",
    bg: "#ffe3e2",
  },
  Intrigue: {
    key: "Intrigue",
    description: "Opens a loop the viewer wants to close.",
    color: "#9d5cf5",
    bg: "#efe2ff",
  },
  Clarify: {
    key: "Clarify",
    description: "Makes the value instantly obvious.",
    color: "#57c884",
    bg: "#dcf8e7",
  },
  Reward: {
    key: "Reward",
    description: "Shows the payoff first, then earns the explanation.",
    color: "#f0b847",
    bg: "#fff2cc",
  },
};

export const categoryMeta: Record<HookCategory, CategoryMeta> = {
  Curiosity: { key: "Curiosity", label: "Curiosity & Mystery", color: "#f0b847" },
  Bold: { key: "Bold", label: "Bold Claims & Contrarian", color: "#ef5d65" },
  Questions: { key: "Questions", label: "Questions & Challenges", color: "#a06af8" },
  Emotional: { key: "Emotional", label: "Emotional Triggers", color: "#db5aa3" },
  Authority: { key: "Authority", label: "Social Proof & Authority", color: "#4d78eb" },
  Visual: { key: "Visual", label: "Visual & Camera Techniques", color: "#35b779" },
  Audio: { key: "Audio", label: "Audio & Sound Design", color: "#5ec874" },
  Editing: { key: "Editing", label: "Editing & Pacing", color: "#ff7d57" },
  Text: { key: "Text", label: "Text & Caption Hooks", color: "#f4a433" },
  Story: { key: "Story", label: "Storytelling & Narrative", color: "#7f78ff" },
  Interrupts: { key: "Interrupts", label: "Pattern Interrupts", color: "#ff6b6b" },
  Education: { key: "Education", label: "Value & Education", color: "#2aa36b" },
};

export const verticalProfiles: VerticalProfile[] = [
  { id: "beauty", name: "Beauty", color: "#f66ab2", prompt: "creator holding product close to camera" },
  { id: "ecommerce", name: "E-Commerce", color: "#4d78eb", prompt: "hands unboxing product on a desk" },
  { id: "fashion", name: "Fashion", color: "#9d5cf5", prompt: "mirror fit check with quick cuts" },
  { id: "luxury", name: "Luxury", color: "#b28a4a", prompt: "slow product detail with soft light" },
  { id: "finance", name: "Finance", color: "#2aa36b", prompt: "screen recording with clean annotations" },
  { id: "gaming", name: "Gaming", color: "#6366f1", prompt: "gameplay moment with creator reaction" },
  { id: "auto", name: "Automotive", color: "#ef5d65", prompt: "walkaround detail with dashboard reveal" },
  { id: "travel", name: "Travel", color: "#22a2c3", prompt: "airport or hotel reveal in first person" },
  { id: "real-estate", name: "Real Estate", color: "#c47d43", prompt: "door opens into a surprising room" },
  { id: "retail", name: "Retail", color: "#ff8c42", prompt: "shelf discovery and price tag reveal" },
];

type HookSeed = Pick<
  Hook,
  | "id"
  | "displayName"
  | "name"
  | "category"
  | "subcategory"
  | "pattern"
  | "intent"
  | "example"
  | "description"
  | "difficulty"
  | "productionTier"
> &
  Partial<Pick<Hook, "secondaryPattern" | "featured">>;

const hookSeeds: HookSeed[] = [
  { id: "curiosity-gap", displayName: "The Gap", name: "The Curiosity Gap", category: "Curiosity", subcategory: "Information Void", pattern: "Intrigue", secondaryPattern: "Clarify", intent: "Curiosity", featured: true, difficulty: "Beginner", productionTier: "Found", example: "I found one thing that 99% of brands are doing wrong - and it's costing them thousands.", description: "The brain can't tolerate an unclosed information loop - it stays on the screen until the missing piece arrives." },
  { id: "countdown-tease", displayName: "The Countdown", name: "The Countdown Tease", category: "Curiosity", subcategory: "Numbered Reveal", pattern: "Intrigue", intent: "Curiosity", difficulty: "Beginner", productionTier: "UGC", example: "3 things they will not say out loud.", description: "Promise a specific count so the viewer mentally commits to finishing the list." },
  { id: "cliffhanger-cut", displayName: "The Cut", name: "The Cliffhanger Cut", category: "Curiosity", subcategory: "Tension Break", pattern: "Reward", intent: "Curiosity", difficulty: "Intermediate", productionTier: "UGC", example: "Show the moment right before the reveal, then cut away.", description: "Interrupt the payoff at the exact frame where anticipation peaks." },
  { id: "mystery-object", displayName: "Mystery Object", name: "The Mystery Object", category: "Curiosity", subcategory: "Visual Mystery", pattern: "Reward", intent: "Curiosity", difficulty: "Intermediate", productionTier: "UGC", example: "Start on an extreme close-up of a strange texture.", description: "Force the visual cortex to solve what it is seeing." },
  { id: "before-you-scroll", displayName: "Scroll Stopper", name: "The Scroll Stopper", category: "Curiosity", subcategory: "Direct Address", pattern: "Intrigue", secondaryPattern: "Interrupt", intent: "Urgency", featured: true, difficulty: "Beginner", productionTier: "UGC", example: "Wait, before you scroll, this can save you 10 hours.", description: "Name the viewer's next action and give them a reason to pause." },
  { id: "bold-claim", displayName: "Bold Claim", name: "The Bold Claim", category: "Bold", subcategory: "Declaration", pattern: "Clarify", intent: "Authority", featured: true, difficulty: "Beginner", productionTier: "UGC", example: "Hashtags are dead. I have the data to prove it.", description: "Lead with a confident, specific assertion that begs for proof." },
  { id: "death-declaration", displayName: "It's Dead", name: "The Death Declaration", category: "Bold", subcategory: "Disruption", pattern: "Intrigue", intent: "Urgency", difficulty: "Beginner", productionTier: "UGC", example: "Email marketing is dead. Here is what replaced it.", description: "Call time of death on a familiar tactic and explain the shift." },
  { id: "i-was-wrong", displayName: "I Was Wrong", name: "The Public Reversal", category: "Bold", subcategory: "Vulnerability", pattern: "Intrigue", intent: "Curiosity", difficulty: "Advanced", productionTier: "UGC", example: "I told you to do this for years. I was wrong.", description: "Admit a public reversal to create credibility and tension." },
  { id: "self-identification", displayName: "For You If", name: "The Self-Identification Call", category: "Questions", subcategory: "Targeting", pattern: "Intrigue", intent: "Curiosity", difficulty: "Beginner", productionTier: "UGC", example: "If you sell without wanting to sound pushy, this is for you.", description: "Qualify the exact viewer before the message begins." },
  { id: "stop-doing-this", displayName: "Stop This", name: "The Stop Command", category: "Questions", subcategory: "Directive", pattern: "Intrigue", secondaryPattern: "Interrupt", intent: "Urgency", difficulty: "Beginner", productionTier: "UGC", example: "Stop posting the same five hashtags every day.", description: "Use a direct command to halt a familiar behavior." },
  { id: "this-or-that", displayName: "This vs That", name: "The This vs. That", category: "Questions", subcategory: "Comparison", pattern: "Intrigue", intent: "Contrast", difficulty: "Intermediate", productionTier: "UGC", example: "CapCut vs Premiere: I tested both for 30 days.", description: "Create a simple binary choice the viewer wants resolved." },
  { id: "fear-of-missing-out", displayName: "FOMO", name: "The FOMO Trigger", category: "Emotional", subcategory: "Scarcity", pattern: "Interrupt", intent: "Urgency", featured: true, difficulty: "Beginner", productionTier: "Studio", example: "Everyone is switching to this while you are still waiting.", description: "Make inaction feel like the risky choice." },
  { id: "shock-value", displayName: "Shock", name: "The Shock Factor", category: "Emotional", subcategory: "Surprise", pattern: "Intrigue", intent: "Story", difficulty: "Intermediate", productionTier: "UGC", example: "I deleted 500 posts from my account. Here is why.", description: "Open with an action that sounds irrational until explained." },
  { id: "transformation-before-after", displayName: "Before/After", name: "The Transformation Reveal", category: "Emotional", subcategory: "Journey", pattern: "Intrigue", intent: "Contrast", featured: true, difficulty: "Intermediate", productionTier: "UGC", example: "Six months ago I had 200 followers. Today, 200K.", description: "Show the distance between old state and new state immediately." },
  { id: "proof-first", displayName: "Proof First", name: "The Proof-First", category: "Authority", subcategory: "Results", pattern: "Intrigue", intent: "Authority", featured: true, difficulty: "Intermediate", productionTier: "Studio", example: "This post got 2.3M views. Let me show you why.", description: "Lead with evidence before asking for trust." },
  { id: "testimonial-flash", displayName: "Testimonial", name: "The Testimonial Flash", category: "Authority", subcategory: "Third Party", pattern: "Intrigue", intent: "Authority", difficulty: "Intermediate", productionTier: "UGC", example: "Flash a DM, then explain the strategy behind the result.", description: "Let a third party create the first credibility signal." },
  { id: "behind-the-scenes", displayName: "Behind Scenes", name: "The Behind The Curtain", category: "Authority", subcategory: "Access", pattern: "Clarify", intent: "Education", difficulty: "Beginner", productionTier: "UGC", example: "Here is what my process actually looks like.", description: "Offer access to the real workflow behind the polished output." },
  { id: "zoom-in-hook", displayName: "Zoom Punch", name: "The Zoom Punch", category: "Visual", subcategory: "Camera Movement", pattern: "Interrupt", intent: "Urgency", difficulty: "Beginner", productionTier: "Studio", example: "Rapid zoom into the face as the first line lands.", description: "Use camera movement as punctuation before the message." },
  { id: "whip-pan", displayName: "Whip Pan", name: "The Whip Pan", category: "Visual", subcategory: "Camera Movement", pattern: "Intrigue", intent: "Curiosity", difficulty: "Intermediate", productionTier: "Studio", example: "Whip from an empty desk to a creator already mid-sentence.", description: "Turn movement into a reveal." },
  { id: "pov-shot", displayName: "POV", name: "The POV Immersion", category: "Visual", subcategory: "Perspective", pattern: "Interrupt", intent: "Urgency", difficulty: "Intermediate", productionTier: "UGC", example: "Camera walks toward the board as the first tip appears.", description: "Make the viewer feel physically inside the moment." },
  { id: "split-screen-compare", displayName: "Split Screen", name: "The Split Screen", category: "Visual", subcategory: "Comparison", pattern: "Intrigue", intent: "Contrast", difficulty: "Intermediate", productionTier: "Studio", example: "Left side: what you do. Right side: what works.", description: "Use simultaneous contrast to make the difference obvious." },
  { id: "face-close-up", displayName: "Face First", name: "The Face-First", category: "Visual", subcategory: "Framing", pattern: "Intrigue", intent: "Curiosity", featured: true, difficulty: "Beginner", productionTier: "UGC", example: "Open on a surprised face before revealing the cause.", description: "Emotion arrives before context." },
  { id: "silence-break", displayName: "Silence", name: "The Silence Break", category: "Audio", subcategory: "Contrast", pattern: "Intrigue", intent: "Curiosity", difficulty: "Beginner", productionTier: "UGC", example: "1.5 seconds of silence, then a loud snap.", description: "Use absence of sound to make the next sound feel huge." },
  { id: "trending-audio", displayName: "Trend Audio", name: "The Trending Audio Ride", category: "Audio", subcategory: "Trend", pattern: "Intrigue", intent: "Curiosity", difficulty: "Beginner", productionTier: "UGC", example: "Ride the trend format, then turn into your own message.", description: "Borrow familiar rhythm, then add a fresh turn." },
  { id: "bass-drop", displayName: "Bass Drop", name: "The Bass Drop", category: "Audio", subcategory: "Music", pattern: "Interrupt", intent: "Urgency", difficulty: "Intermediate", productionTier: "UGC", example: "Music builds, drop hits exactly as the claim appears.", description: "Synchronize sound and visual impact." },
  { id: "jump-cut-rapid", displayName: "Jump Cut", name: "The Rapid-Fire Jump Cut", category: "Editing", subcategory: "Speed", pattern: "Intrigue", intent: "Curiosity", difficulty: "Intermediate", productionTier: "UGC", example: "Four angles in two seconds, one sentence across all cuts.", description: "Make pace itself the first hook." },
  { id: "speed-ramp", displayName: "Speed Ramp", name: "The Speed Ramp", category: "Editing", subcategory: "Tempo", pattern: "Clarify", intent: "Education", difficulty: "Intermediate", productionTier: "Studio", example: "Slow walk ramps to normal as the promise lands.", description: "Use tempo change to guide attention into the point." },
  { id: "freeze-frame", displayName: "Freeze + Label", name: "The Freeze + Label", category: "Editing", subcategory: "Annotation", pattern: "Interrupt", intent: "Education", difficulty: "Intermediate", productionTier: "Studio", example: "Freeze the frame, label what viewers should notice.", description: "Stop motion and annotate the value." },
  { id: "glitch-effect", displayName: "Glitch", name: "The Glitch Effect", category: "Editing", subcategory: "Disruption", pattern: "Interrupt", intent: "Urgency", difficulty: "Intermediate", productionTier: "AI", example: "Clean shot glitches, then resets with the corrected message.", description: "Use a generated visual error to reset attention." },
  { id: "rewind-hook", displayName: "Rewind", name: "The Rewind", category: "Editing", subcategory: "Time Manipulation", pattern: "Interrupt", intent: "Urgency", difficulty: "Intermediate", productionTier: "UGC", example: "Show the finished result, rewind, then teach the build.", description: "Begin at the end and travel backward." },
  { id: "b-roll-cut-away", displayName: "B-Roll Open", name: "The B-Roll Montage Open", category: "Editing", subcategory: "Visual Richness", pattern: "Reward", intent: "Authority", difficulty: "Intermediate", productionTier: "Studio", example: "Hands, screen, notebook, result, then the lesson.", description: "Make production texture the first proof of taste." },
  { id: "text-first", displayName: "Text First", name: "The Text-First", category: "Text", subcategory: "Opening Text", pattern: "Intrigue", intent: "Curiosity", difficulty: "Beginner", productionTier: "Found", example: "Black screen: Stop posting at 9 AM.", description: "Let text create the first beat before the creator appears." },
  { id: "kinetic-typography", displayName: "Kinetic Type", name: "The Kinetic Typography", category: "Text", subcategory: "Animated Text", pattern: "Intrigue", intent: "Curiosity", difficulty: "Intermediate", productionTier: "AI", example: "THIS ONE TRICK flies in word by word.", description: "Generate animated words so reading becomes motion." },
  { id: "story-open", displayName: "Cold Open", name: "The Cold Open Story", category: "Story", subcategory: "In Medias Res", pattern: "Intrigue", intent: "Story", difficulty: "Intermediate", productionTier: "UGC", example: "So there I was, watching the post hit one million.", description: "Drop the viewer into the middle of the story." },
  { id: "plot-twist", displayName: "Plot Twist", name: "The Plot Twist Tease", category: "Story", subcategory: "Surprise", pattern: "Intrigue", intent: "Story", difficulty: "Intermediate", productionTier: "UGC", example: "I did everything right. That was the problem.", description: "Promise that the expected explanation is wrong." },
  { id: "storytime", displayName: "Storytime", name: "The Storytime Setup", category: "Story", subcategory: "Personal", pattern: "Intrigue", intent: "Story", difficulty: "Beginner", productionTier: "UGC", example: "Storytime: the client almost killed the campaign.", description: "Use personal framing to make the lesson feel witnessed." },
  { id: "dialogue-hook", displayName: "Dialogue", name: "The Dialogue Hook", category: "Story", subcategory: "Conversation", pattern: "Interrupt", intent: "Story", difficulty: "Intermediate", productionTier: "UGC", example: "Them: this will never work. Me: watch this.", description: "Start inside a conversation so the viewer catches up." },
  { id: "visual-pattern-interrupt", displayName: "Visual Break", name: "The Visual Shatter", category: "Interrupts", subcategory: "Visual Break", pattern: "Interrupt", intent: "Urgency", difficulty: "Intermediate", productionTier: "AI", example: "A normal talking head is interrupted by a sudden object.", description: "Break the expected visual pattern with a generated insert and then explain why." },
  { id: "expectations-subvert", displayName: "Subversion", name: "The Expectation Subvert", category: "Interrupts", subcategory: "Misdirection", pattern: "Interrupt", intent: "Urgency", difficulty: "Advanced", productionTier: "UGC", example: "This should not work. It outperformed everything.", description: "State the opposite of the viewer's assumption." },
  { id: "instant-value", displayName: "Instant Value", name: "The Instant Value Drop", category: "Education", subcategory: "Immediate Payoff", pattern: "Intrigue", intent: "Education", difficulty: "Beginner", productionTier: "UGC", example: "Free tool: remove any background in two seconds.", description: "Give value before explaining the frame." },
  { id: "hack-reveal", displayName: "Hack", name: "The Hidden Hack", category: "Education", subcategory: "Shortcut", pattern: "Intrigue", intent: "Exclusive", difficulty: "Beginner", productionTier: "UGC", example: "CapCut hack most editors miss: hold shift while dragging.", description: "Frame a small workflow improvement as hidden leverage." },
  { id: "tool-demo", displayName: "Tool Demo", name: "The Tool Demo", category: "Education", subcategory: "Tutorial", pattern: "Intrigue", intent: "Education", difficulty: "Beginner", productionTier: "UGC", example: "Open tool, apply effect, show before and after.", description: "Let the screen prove the utility before narration." },
  { id: "step-by-step", displayName: "Steps", name: "The Step-by-Step", category: "Education", subcategory: "Process", pattern: "Intrigue", intent: "Education", difficulty: "Beginner", productionTier: "Found", example: "Steal my 3-step posting checklist.", description: "Promise a process the viewer can follow immediately." },
  { id: "save-this", displayName: "Save This", name: "The Save-This Reference", category: "Education", subcategory: "Reference", pattern: "Clarify", intent: "Education", difficulty: "Beginner", productionTier: "Studio", example: "Save this before your next launch.", description: "Position the post as a utility object, not just entertainment." },
];

const palettes: Array<[string, string]> = [
  ["#b88348", "#24130b"],
  ["#eee6cf", "#6d5844"],
  ["#d5e5cd", "#194c38"],
  ["#f5c1b1", "#48251c"],
  ["#c9d8f0", "#25385c"],
  ["#f4e378", "#3d3500"],
  ["#d9c1f6", "#35214e"],
  ["#a9dfcb", "#0f3a34"],
];

const referenceMedia = [
  {
    id: "mdn-flower",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "mdn-flower-webm",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm",
  },
  {
    id: "w3c-sintel",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.mp4",
  },
  {
    id: "w3c-sintel-webm",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.webm",
  },
  {
    id: "w3c-bunny",
    videoUrl: "https://media.w3.org/2010/05/bunny/trailer.mp4",
  },
  {
    id: "w3c-demo",
    videoUrl: "https://media.w3.org/2010/05/video/movie_300.mp4",
  },
  {
    id: "w3c-demo-webm",
    videoUrl: "https://media.w3.org/2010/05/video/movie_300.webm",
  },
];

export const mediaHookMatrix: MediaHookMatch[] = [
  {
    id: "sm-bitmoji-twinning",
    title: "Steve Madden Bitmoji Twinning",
    sourcePath: "/media/references/sm-bitmoji-twinning.gif",
    productVertical: "Fashion footwear / creator try-on",
    fitConfidence: "strong",
    visualTraits: ["creator full-body fit", "avatar side-by-side", "matching red boots", "playful social overlay"],
    scriptSignals: ["twinning with my Bitmoji", "outfit match", "creator partnership"],
    primaryHookIds: ["split-screen-compare", "visual-pattern-interrupt", "this-or-that"],
    secondaryHookIds: ["transformation-before-after", "proof-first", "face-close-up"],
    suggestedCategoryIds: ["digital-double", "persona-match"],
    bestFor: ["side-by-side comparison", "avatar/product resemblance", "fashion social proof"],
    avoidFor: ["serious authority claims", "dense educational explainers"],
  },
  {
    id: "sm-date-night",
    title: "Steve Madden Date Night Fit",
    sourcePath: "/media/references/sm-date-night.gif",
    productVertical: "Fashion footwear / occasion styling",
    fitConfidence: "medium",
    visualTraits: ["editorial title overlay", "creator outfit reveal", "soft glam room", "date-night positioning"],
    scriptSignals: ["Date Night", "occasion-first styling", "brand feature"],
    primaryHookIds: ["text-first", "face-close-up", "self-identification"],
    secondaryHookIds: ["proof-first", "b-roll-cut-away", "kinetic-typography"],
    suggestedCategoryIds: ["occasion-fit", "style-context"],
    bestFor: ["occasion-based hooks", "fashion mood boards", "text-led openings"],
    avoidFor: ["urgent warnings", "hard contrast demos"],
  },
  {
    id: "sm-summer-festival-shoes",
    title: "Steve Madden Two Festival Shoes",
    sourcePath: "/media/references/sm-summer-festival-shoes.gif",
    productVertical: "Fashion footwear / seasonal product picks",
    fitConfidence: "strong",
    visualTraits: ["creator talking head", "two products held to camera", "large headline text", "seasonal festival angle"],
    scriptSignals: ["The 2 shoes you'll need", "summer festivals", "numbered recommendation"],
    primaryHookIds: ["countdown-tease", "this-or-that", "instant-value"],
    secondaryHookIds: ["save-this", "step-by-step", "tool-demo"],
    suggestedCategoryIds: ["two-pick-edit", "seasonal-buying-guide"],
    bestFor: ["numbered lists", "product comparison", "seasonal buying guides"],
    avoidFor: ["mystery reveals without visible product", "abstract story hooks"],
  },
  {
    id: "sm-boots-forecast-pov",
    title: "Steve Madden Boots Forecast POV",
    sourcePath: "/media/references/sm-boots-forecast-pov.gif",
    productVertical: "Fashion footwear / unboxing forecast",
    fitConfidence: "medium",
    visualTraits: ["creator holds shoe box", "POV headline", "forecast framing", "clean close-up composition"],
    scriptSignals: ["POV", "boots forecast", "unboxing setup"],
    primaryHookIds: ["pov-shot", "mystery-object", "before-you-scroll"],
    secondaryHookIds: ["curiosity-gap", "text-first", "whip-pan"],
    suggestedCategoryIds: ["trend-forecast", "box-reveal"],
    bestFor: ["POV setup", "box reveal", "trend forecast"],
    avoidFor: ["proof-heavy authority", "rapid edit hooks"],
  },
  {
    id: "sm-closet-update",
    title: "Steve Madden Closet Update",
    sourcePath: "/media/references/sm-closet-update.gif",
    productVertical: "Fashion footwear / closet refresh",
    fitConfidence: "medium",
    visualTraits: ["creator movement", "wide room shot", "closet refresh prompt", "high-energy reveal"],
    scriptSignals: ["time to update your closet", "outfit transition", "movement-led UGC"],
    primaryHookIds: ["before-you-scroll", "stop-doing-this", "zoom-in-hook"],
    secondaryHookIds: ["transformation-before-after", "rewind-hook", "bass-drop"],
    suggestedCategoryIds: ["closet-reset", "seasonal-refresh"],
    bestFor: ["direct CTA hooks", "energetic outfit reveal", "seasonal wardrobe refresh"],
    avoidFor: ["quiet mystery loops", "studio product-only proof"],
  },
  {
    id: "ramadan-health-advice",
    title: "Ramadan Health Advice",
    sourcePath: "/media/references/ramadan-health-advice.mp4",
    productVertical: "Health education / cultural moment",
    fitConfidence: "medium",
    visualTraits: ["advice-led creator video", "seasonal Ramadan context", "education-first framing"],
    scriptSignals: ["Ramadan health advice", "fast practical guidance", "cultural timing"],
    primaryHookIds: ["instant-value", "save-this", "step-by-step"],
    secondaryHookIds: ["proof-first", "behind-the-scenes"],
    suggestedCategoryIds: ["cultural-moment-advice", "wellness-ritual"],
    bestFor: ["seasonal education", "saveable advice", "Ramadan-specific utility"],
    avoidFor: ["pure product reveal", "visual-only pattern interrupts"],
  },
  {
    id: "bolt-reference",
    title: "Bolt Reference",
    sourcePath: "/media/references/bolt.mp4",
    productVertical: "Unreviewed reference / app or service",
    fitConfidence: "gap",
    visualTraits: ["file needs manual review", "brand or product reference"],
    scriptSignals: ["Bolt"],
    primaryHookIds: [],
    secondaryHookIds: [],
    suggestedCategoryIds: ["unreviewed-reference", "app-service-proof"],
    bestFor: ["holding area until the first frame and script are reviewed"],
    avoidFor: ["automatic hook-card assignment"],
  },
  {
    id: "ugc-ref-a795",
    title: "Unreviewed UGC Reference A795",
    sourcePath: "/media/references/ugc-ref-a795.mp4",
    productVertical: "Unreviewed UGC reference",
    fitConfidence: "gap",
    visualTraits: ["file needs manual review"],
    scriptSignals: ["unknown"],
    primaryHookIds: [],
    secondaryHookIds: [],
    suggestedCategoryIds: ["unreviewed-reference"],
    bestFor: ["inspiration intake", "manual tagging pass"],
    avoidFor: ["automatic hook-card assignment"],
  },
  {
    id: "ugc-ref-3fd78",
    title: "Unreviewed UGC Reference 3FD78",
    sourcePath: "/media/references/ugc-ref-3fd78.mp4",
    productVertical: "Unreviewed UGC reference",
    fitConfidence: "gap",
    visualTraits: ["file needs manual review"],
    scriptSignals: ["unknown"],
    primaryHookIds: [],
    secondaryHookIds: [],
    suggestedCategoryIds: ["unreviewed-reference"],
    bestFor: ["inspiration intake", "manual tagging pass"],
    avoidFor: ["automatic hook-card assignment"],
  },
  {
    id: "ugc-ref-ac055",
    title: "Unreviewed UGC Reference AC055",
    sourcePath: "/media/references/ugc-ref-ac055.mp4",
    productVertical: "Unreviewed UGC reference",
    fitConfidence: "gap",
    visualTraits: ["file needs manual review"],
    scriptSignals: ["unknown"],
    primaryHookIds: [],
    secondaryHookIds: [],
    suggestedCategoryIds: ["unreviewed-reference"],
    bestFor: ["inspiration intake", "manual tagging pass"],
    avoidFor: ["automatic hook-card assignment"],
  },
  {
    id: "ugc-ref-e8dfa",
    title: "Unreviewed UGC Reference E8DFA",
    sourcePath: "/media/references/ugc-ref-e8dfa.mp4",
    productVertical: "Unreviewed UGC reference",
    fitConfidence: "gap",
    visualTraits: ["file needs manual review"],
    scriptSignals: ["unknown"],
    primaryHookIds: [],
    secondaryHookIds: [],
    suggestedCategoryIds: ["unreviewed-reference"],
    bestFor: ["inspiration intake", "manual tagging pass"],
    avoidFor: ["automatic hook-card assignment"],
  },
  {
    id: "ramadan-beauty-makeup",
    title: "Ramadan Beauty Makeup",
    sourcePath: "/media/references/ramadan-beauty-makeup.mp4",
    productVertical: "Beauty / Ramadan routine",
    fitConfidence: "medium",
    visualTraits: ["beauty routine", "seasonal Ramadan context", "creator-led tutorial"],
    scriptSignals: ["Ramadan beauty makeup", "routine", "occasion prep"],
    primaryHookIds: ["step-by-step", "tool-demo", "save-this"],
    secondaryHookIds: ["instant-value", "face-close-up"],
    suggestedCategoryIds: ["cultural-moment-advice", "occasion-routine"],
    bestFor: ["beauty routine", "seasonal tutorial", "saveable steps"],
    avoidFor: ["hard urgency", "abstract visual stunts"],
  },
  {
    id: "ramadan-salad-iftar-suhoor",
    title: "Ramadan Salad for Iftar and Suhoor",
    sourcePath: "/media/references/ramadan-salad-iftar-suhoor.mp4",
    productVertical: "Food / Ramadan recipe",
    fitConfidence: "strong",
    visualTraits: ["recipe or food prep", "Ramadan meal timing", "two-use-case framing"],
    scriptSignals: ["salad", "iftar", "suhoor"],
    primaryHookIds: ["step-by-step", "instant-value", "save-this"],
    secondaryHookIds: ["this-or-that", "tool-demo"],
    suggestedCategoryIds: ["meal-timing-split", "cultural-moment-advice"],
    bestFor: ["recipe tutorial", "dual-use food content", "Ramadan utility"],
    avoidFor: ["fashion styling", "brand-collab reveal"],
  },
  {
    id: "snack-product-hold-excited",
    title: "Snack Product Hold Excited",
    sourcePath: "/media/references/snack-product-hold-excited.gif",
    productVertical: "Snack / creator product reaction",
    fitConfidence: "medium",
    visualTraits: ["creator holds multiple packs", "excited face", "bright product packaging"],
    scriptSignals: ["product discovery", "taste-test setup", "creator reaction"],
    primaryHookIds: ["face-close-up", "proof-first", "testimonial-flash"],
    secondaryHookIds: ["before-you-scroll", "save-this"],
    suggestedCategoryIds: ["taste-test-setup", "product-haul-intro"],
    bestFor: ["creator reaction", "product haul", "snack discovery"],
    avoidFor: ["silent object-only visuals", "serious authority claims"],
  },
  {
    id: "snack-which-one-plate",
    title: "Snack Which One Plate",
    sourcePath: "/media/references/snack-which-one-plate.gif",
    productVertical: "Snack / interactive choice",
    fitConfidence: "strong",
    visualTraits: ["empty plate", "handheld setup", "small text prompt", "choice-game format"],
    scriptSignals: ["which one are you", "interactive prompt", "viewer identity"],
    primaryHookIds: ["this-or-that", "self-identification", "mystery-object"],
    secondaryHookIds: ["curiosity-gap", "text-first"],
    suggestedCategoryIds: ["choice-game", "interactive-identity"],
    bestFor: ["viewer participation", "comment bait without heavy script", "snack choice game"],
    avoidFor: ["straight product proof", "long educational explanation"],
  },
  {
    id: "snack-silent-review",
    title: "Snack Silent Review",
    sourcePath: "/media/references/snack-silent-review.gif",
    productVertical: "Snack / silent review",
    fitConfidence: "gap",
    visualTraits: ["creator holds product", "silent review text", "facial reaction carries the review"],
    scriptSignals: ["Silent Review", "no spoken line", "reaction-only evaluation"],
    primaryHookIds: [],
    secondaryHookIds: ["silence-break", "testimonial-flash", "proof-first"],
    suggestedCategoryIds: ["silent-review", "reaction-review"],
    bestFor: ["reaction-only product review", "sound-off browsing", "taste test"],
    avoidFor: ["talking-head scripts", "copy-heavy explainers"],
  },
  {
    id: "snack-product-face-animate",
    title: "Snack Product Face Animation",
    sourcePath: "/media/references/snack-product-face-animate.gif",
    productVertical: "Snack / animated product persona",
    fitConfidence: "strong",
    visualTraits: ["product pack with animated face", "object gets personality", "visual joke"],
    scriptSignals: ["product character", "animated pack", "surreal product behavior"],
    primaryHookIds: ["visual-pattern-interrupt", "mystery-object", "glitch-effect"],
    secondaryHookIds: ["shock-value", "text-first"],
    suggestedCategoryIds: ["product-persona", "animated-pack"],
    bestFor: ["product personality", "visual interruption", "snack entertainment"],
    avoidFor: ["plain educational advice", "realistic product proof"],
  },
  {
    id: "mom-baby-unboxing",
    title: "Baby Room Unboxing",
    sourcePath: "/media/references/mom-baby-unboxing.gif",
    productVertical: "Parenting / nursery unboxing",
    fitConfidence: "medium",
    visualTraits: ["parent unboxes nursery items", "room context", "soft lifestyle scene"],
    scriptSignals: ["unboxing", "nursery setup", "parenting use case"],
    primaryHookIds: ["behind-the-scenes", "b-roll-cut-away", "story-open"],
    secondaryHookIds: ["tool-demo", "save-this"],
    suggestedCategoryIds: ["use-case-unboxing", "room-reset"],
    bestFor: ["lifestyle unboxing", "nursery setup", "parenting product context"],
    avoidFor: ["hard pattern interrupts", "urgent warning hooks"],
  },
  {
    id: "food-market-perspective",
    title: "Food Market Forced Perspective",
    sourcePath: "/media/references/food-market-perspective.gif",
    productVertical: "Retail / forced perspective location",
    fitConfidence: "strong",
    visualTraits: ["forced perspective pinch", "market location", "POV hand gesture", "wayfinding sign"],
    scriptSignals: ["location reveal", "visual illusion", "destination cue"],
    primaryHookIds: ["visual-pattern-interrupt", "pov-shot", "mystery-object"],
    secondaryHookIds: ["whip-pan", "zoom-in-hook"],
    suggestedCategoryIds: ["forced-perspective", "location-reveal"],
    bestFor: ["place reveal", "retail destination", "POV visual trick"],
    avoidFor: ["product education", "testimonial proof"],
  },
  {
    id: "loewe-on-collab-throw",
    title: "Loewe x On Collab Throw",
    sourcePath: "/media/references/loewe-on-collab-throw.gif",
    productVertical: "Luxury fashion / brand collaboration",
    fitConfidence: "medium",
    visualTraits: ["brand logos", "minimal wall", "hand toss", "collab signal"],
    scriptSignals: ["brand collaboration", "drop tease", "luxury reveal"],
    primaryHookIds: ["text-first", "b-roll-cut-away", "proof-first"],
    secondaryHookIds: ["mystery-object", "before-you-scroll"],
    suggestedCategoryIds: ["collab-reveal", "drop-signal"],
    bestFor: ["brand collaboration", "drop tease", "minimal luxury visual"],
    avoidFor: ["creator reaction", "step-by-step tutorial"],
  },
  {
    id: "sneaker-product-detail",
    title: "Sneaker Product Detail",
    sourcePath: "/media/references/sneaker-product-detail.gif",
    productVertical: "Footwear / product detail",
    fitConfidence: "strong",
    visualTraits: ["macro shoe close-up", "clean studio movement", "material and sole detail"],
    scriptSignals: ["product detail", "feature proof", "premium texture"],
    primaryHookIds: ["b-roll-cut-away", "proof-first", "mystery-object"],
    secondaryHookIds: ["zoom-in-hook", "save-this"],
    suggestedCategoryIds: ["macro-product-proof", "detail-first"],
    bestFor: ["product feature proof", "premium material detail", "footwear close-up"],
    avoidFor: ["talking-head confession", "comment-choice prompts"],
  },
  {
    id: "adidas-ar-box-reveal",
    title: "Adidas AR Box Reveal",
    sourcePath: "/media/references/adidas-ar-box-reveal.gif",
    productVertical: "Footwear / augmented product reveal",
    fitConfidence: "strong",
    visualTraits: ["shoe box", "phone overlay", "AR-style reveal", "product inside packaging"],
    scriptSignals: ["unboxing", "augmented reveal", "digital overlay"],
    primaryHookIds: ["mystery-object", "visual-pattern-interrupt", "glitch-effect"],
    secondaryHookIds: ["pov-shot", "proof-first"],
    suggestedCategoryIds: ["ar-overlay-reveal", "box-reveal"],
    bestFor: ["digital product reveal", "unboxing with overlay", "footwear tech visual"],
    avoidFor: ["soft lifestyle story", "pure text-first cards"],
  },
  {
    id: "giant-box-surreal-ooh",
    title: "Giant Box Surreal OOH",
    sourcePath: "/media/references/giant-box-surreal-ooh.gif",
    productVertical: "Retail / CGI outdoor stunt",
    fitConfidence: "strong",
    visualTraits: ["giant floating box", "outdoor scene", "surreal scale", "CGI stunt"],
    scriptSignals: ["oversized object", "public stunt", "impossible scene"],
    primaryHookIds: ["visual-pattern-interrupt", "shock-value", "mystery-object"],
    secondaryHookIds: ["expectations-subvert", "glitch-effect"],
    suggestedCategoryIds: ["surreal-scale", "cgi-ooh"],
    bestFor: ["impossible product scale", "outdoor stunt", "CGI attention grab"],
    avoidFor: ["practical education", "quiet review formats"],
  },
  {
    id: "ursa-major-minimal-product",
    title: "Ursa Major Minimal Product Slide",
    sourcePath: "/media/references/ursa-major-minimal-product.gif",
    productVertical: "Personal care / minimalist product loop",
    fitConfidence: "medium",
    visualTraits: ["single product on color field", "negative space", "clean pack movement"],
    scriptSignals: ["minimal product reveal", "deodorant pack shot"],
    primaryHookIds: ["b-roll-cut-away", "mystery-object"],
    secondaryHookIds: ["proof-first", "text-first"],
    suggestedCategoryIds: ["minimal-pack-shot", "negative-space-product"],
    bestFor: ["premium pack reveal", "clean product loop", "deck or ad background"],
    avoidFor: ["UGC creator proof", "urgent spoken claims"],
  },
  {
    id: "filling-pieces-48h-sale",
    title: "Filling Pieces 48 Hour Sale",
    sourcePath: "/media/references/filling-pieces-48h-sale.gif",
    productVertical: "Footwear / timed sale",
    fitConfidence: "strong",
    visualTraits: ["product hero", "48 hour sale text", "rotating kinetic type", "warm studio lighting"],
    scriptSignals: ["48 hour sale", "up to 50% off", "limited time"],
    primaryHookIds: ["fear-of-missing-out", "text-first", "kinetic-typography"],
    secondaryHookIds: ["before-you-scroll", "proof-first"],
    suggestedCategoryIds: ["timed-sale", "kinetic-offer"],
    bestFor: ["sale urgency", "limited-time footwear drop", "offer-led creative"],
    avoidFor: ["soft education", "silent review"],
  },
  {
    id: "red-bottle-silhouette",
    title: "Red Bottle Silhouette Reveal",
    sourcePath: "/media/references/red-bottle-silhouette.gif",
    productVertical: "Food or CPG / silhouette reveal",
    fitConfidence: "strong",
    visualTraits: ["dark product silhouette", "bright color field", "recognizable bottle shape"],
    scriptSignals: ["guess the product", "shape-first reveal"],
    primaryHookIds: ["mystery-object", "curiosity-gap", "cliffhanger-cut"],
    secondaryHookIds: ["visual-pattern-interrupt", "text-first"],
    suggestedCategoryIds: ["silhouette-reveal"],
    bestFor: ["brand-shape recognition", "guessing game", "product reveal loop"],
    avoidFor: ["testimonial proof", "long tutorial"],
  },
  {
    id: "kenco-ingredient-layout",
    title: "Kenco Ingredient Layout",
    sourcePath: "/media/references/kenco-ingredient-layout.gif",
    productVertical: "Beverage / ingredient proof",
    fitConfidence: "strong",
    visualTraits: ["overhead ingredients", "hand taps bottle", "bright produce layout"],
    scriptSignals: ["ingredient proof", "what is inside", "freshness cue"],
    primaryHookIds: ["proof-first", "b-roll-cut-away", "instant-value"],
    secondaryHookIds: ["tool-demo", "save-this"],
    suggestedCategoryIds: ["ingredient-proof", "overhead-layout"],
    bestFor: ["functional beverage proof", "ingredient storytelling", "freshness claim"],
    avoidFor: ["fashion styling", "creator confession"],
  },
  {
    id: "sneaker-sky-product-grid",
    title: "Sneaker Sky Product Grid",
    sourcePath: "/media/references/sneaker-sky-product-grid.gif",
    productVertical: "Footwear / range showcase",
    fitConfidence: "strong",
    visualTraits: ["nine-tile grid", "shoe held against sky", "range of styles"],
    scriptSignals: ["collection showcase", "multiple options", "style range"],
    primaryHookIds: ["split-screen-compare", "this-or-that", "b-roll-cut-away"],
    secondaryHookIds: ["countdown-tease", "proof-first"],
    suggestedCategoryIds: ["range-grid", "product-menu"],
    bestFor: ["collection reveal", "style comparison", "product menu"],
    avoidFor: ["single-claim authority", "one-person story"],
  },
  {
    id: "jordan-box-tilt",
    title: "Jordan Box Tilt",
    sourcePath: "/media/references/jordan-box-tilt.gif",
    productVertical: "Footwear / premium box reveal",
    fitConfidence: "strong",
    visualTraits: ["black shoe box", "hand tilt", "brand mark", "studio product motion"],
    scriptSignals: ["box reveal", "premium packaging", "drop tease"],
    primaryHookIds: ["mystery-object", "proof-first", "b-roll-cut-away"],
    secondaryHookIds: ["cliffhanger-cut", "text-first"],
    suggestedCategoryIds: ["box-reveal", "premium-packaging"],
    bestFor: ["sneaker drop tease", "packaging proof", "luxury unboxing"],
    avoidFor: ["creator talking head", "how-to advice"],
  },
  {
    id: "heinz-organic-product",
    title: "Heinz Organic Product Hero",
    sourcePath: "/media/references/heinz-organic-product.gif",
    productVertical: "CPG / product claim",
    fitConfidence: "medium",
    visualTraits: ["front-facing pack", "brand logo", "organic claim", "kitchen setting"],
    scriptSignals: ["organic certified", "classic brand proof"],
    primaryHookIds: ["proof-first", "text-first"],
    secondaryHookIds: ["b-roll-cut-away", "save-this"],
    suggestedCategoryIds: ["certification-proof", "pack-claim"],
    bestFor: ["label claim proof", "brand recall", "CPG product hero"],
    avoidFor: ["mystery-first content", "creator drama"],
  },
  {
    id: "turning-red-streaming-title",
    title: "Turning Red Streaming Title Card",
    sourcePath: "/media/references/turning-red-streaming-title.gif",
    productVertical: "Streaming / title availability",
    fitConfidence: "medium",
    visualTraits: ["bold title card", "streaming availability", "solid brand color"],
    scriptSignals: ["now streaming", "original movie", "title drop"],
    primaryHookIds: ["text-first", "bold-claim"],
    secondaryHookIds: ["fear-of-missing-out", "save-this"],
    suggestedCategoryIds: ["streaming-title-card", "availability-drop"],
    bestFor: ["release announcement", "streaming availability", "title-first creative"],
    avoidFor: ["UGC product proof", "visual mystery"],
  },
  {
    id: "probears-pdp-match",
    title: "Probears PDP Match",
    sourcePath: "/media/references/probears-pdp-match.gif",
    productVertical: "Supplement / ecommerce proof",
    fitConfidence: "strong",
    visualTraits: ["phone product page", "physical bottle beside phone", "finger interaction"],
    scriptSignals: ["what you see is what arrives", "PDP proof", "shop page match"],
    primaryHookIds: ["proof-first", "tool-demo", "split-screen-compare"],
    secondaryHookIds: ["b-roll-cut-away", "instant-value"],
    suggestedCategoryIds: ["pdp-match", "ecommerce-proof"],
    bestFor: ["ecommerce trust", "product-page proof", "supplement demo"],
    avoidFor: ["fashion mood content", "abstract story"],
  },
  {
    id: "arabic-bonita-offer-proof",
    title: "Arabic Bonita Offer Proof",
    sourcePath: "/media/references/arabic-bonita-offer-proof.gif",
    productVertical: "Beauty / Arabic offer proof",
    fitConfidence: "medium",
    visualTraits: ["creator close-up", "skin proof inserts", "price/offer overlay", "Arabic text"],
    scriptSignals: ["offer", "monthly payment", "skin benefit"],
    primaryHookIds: ["proof-first", "bold-claim", "instant-value"],
    secondaryHookIds: ["self-identification", "testimonial-flash"],
    suggestedCategoryIds: ["offer-proof-stack", "localized-commerce"],
    bestFor: ["social commerce offer", "beauty proof", "localized promo"],
    avoidFor: ["clean brand-only packshot", "silent aesthetic B-roll"],
  },
  {
    id: "creator-yellow-caption-block",
    title: "Creator Yellow Caption Block",
    sourcePath: "/media/references/creator-yellow-caption-block.gif",
    productVertical: "UGC / caption block setup",
    fitConfidence: "gap",
    visualTraits: ["face close-up", "large blank caption block", "creator expression"],
    scriptSignals: ["caption block to be filled", "talking head template"],
    primaryHookIds: [],
    secondaryHookIds: ["text-first", "face-close-up"],
    suggestedCategoryIds: ["caption-template", "blank-hook-card"],
    bestFor: ["template intake", "caption-driven creator ad"],
    avoidFor: ["automatic hook assignment until text is known"],
  },
  {
    id: "weekday-loading-retail",
    title: "Weekday Loading Retail Card",
    sourcePath: "/media/references/weekday-loading-retail.gif",
    productVertical: "Retail / loading anticipation",
    fitConfidence: "strong",
    visualTraits: ["loading bar", "weekday text", "solid red brand field"],
    scriptSignals: ["weekday loading", "anticipation", "retail reveal"],
    primaryHookIds: ["countdown-tease", "text-first", "curiosity-gap"],
    secondaryHookIds: ["before-you-scroll", "fear-of-missing-out"],
    suggestedCategoryIds: ["loading-tease", "anticipation-card"],
    bestFor: ["countdown/anticipation", "retail drop tease", "text-first suspense"],
    avoidFor: ["creator trust proof", "product detail"],
  },
  {
    id: "hajj-public-service-crowd",
    title: "Hajj Public Service Crowd",
    sourcePath: "/media/references/hajj-public-service-crowd.gif",
    productVertical: "Public service / pilgrimage logistics",
    fitConfidence: "medium",
    visualTraits: ["large crowd", "official logos", "Arabic headline", "public information"],
    scriptSignals: ["official guidance", "transport/logistics", "Hajj context"],
    primaryHookIds: ["proof-first", "text-first", "save-this"],
    secondaryHookIds: ["instant-value", "save-this"],
    suggestedCategoryIds: ["public-service-announcement", "crowd-guidance"],
    bestFor: ["official announcement", "public logistics", "cultural moment"],
    avoidFor: ["product selling", "creator entertainment"],
  },
  {
    id: "arabic-comment-reply-makeup",
    title: "Arabic Comment Reply Makeup",
    sourcePath: "/media/references/arabic-comment-reply-makeup.gif",
    productVertical: "Beauty / comment reply tutorial",
    fitConfidence: "strong",
    visualTraits: ["reply-to-comment bubble", "creator speaking", "makeup challenge request"],
    scriptSignals: ["reply to comment", "I challenge you", "makeup look"],
    primaryHookIds: ["testimonial-flash", "tool-demo", "self-identification"],
    secondaryHookIds: ["step-by-step", "face-close-up"],
    suggestedCategoryIds: ["comment-reply", "audience-challenge"],
    bestFor: ["audience request", "beauty tutorial", "social proof from comments"],
    avoidFor: ["brand-only product hero", "silent B-roll"],
  },
  {
    id: "gaming-sneaker-controller",
    title: "Gaming Sneaker Controller",
    sourcePath: "/media/references/gaming-sneaker-controller.gif",
    productVertical: "Footwear / gaming metaphor",
    fitConfidence: "strong",
    visualTraits: ["game controller foreground", "shoe on platform", "ring light", "playable product metaphor"],
    scriptSignals: ["control the shoe", "gaming visual metaphor", "product as game object"],
    primaryHookIds: ["pov-shot", "visual-pattern-interrupt", "mystery-object"],
    secondaryHookIds: ["glitch-effect", "proof-first"],
    suggestedCategoryIds: ["game-controller-demo", "playable-product"],
    bestFor: ["gaming audience", "footwear interaction", "POV product control"],
    avoidFor: ["serious finance proof", "wellness advice"],
  },
  {
    id: "bepanthen-creator-overlay",
    title: "Bepanthen Creator Product Overlay",
    sourcePath: "/media/references/bepanthen-creator-overlay.gif",
    productVertical: "Skincare / creator product overlay",
    fitConfidence: "medium",
    visualTraits: ["creator close-up", "floating product overlay", "brand logo"],
    scriptSignals: ["skin moisturizer", "product recommendation", "creator trust"],
    primaryHookIds: ["face-close-up", "testimonial-flash", "proof-first"],
    secondaryHookIds: ["self-identification", "tool-demo"],
    suggestedCategoryIds: ["floating-product-overlay", "creator-recommendation"],
    bestFor: ["creator skincare recommendation", "product overlay ad", "beauty trust"],
    avoidFor: ["minimal packshot", "location reveal"],
  },
  {
    id: "bonita-snap-offer",
    title: "Bonita Snap Offer",
    sourcePath: "/media/references/bonita-snap-offer.gif",
    productVertical: "Beauty / Snapchat-style offer",
    fitConfidence: "medium",
    visualTraits: ["Snapchat ad frame", "beauty proof inserts", "Arabic offer text", "order now CTA"],
    scriptSignals: ["deal", "payment plan", "proof montage"],
    primaryHookIds: ["proof-first", "instant-value", "bold-claim"],
    secondaryHookIds: ["fear-of-missing-out", "testimonial-flash"],
    suggestedCategoryIds: ["snap-offer-stack", "localized-commerce"],
    bestFor: ["performance beauty ad", "Arabic offer creative", "proof plus CTA"],
    avoidFor: ["editorial brand film", "slow product aesthetic"],
  },
  {
    id: "bitpanda-card-proof",
    title: "Bitpanda Card Proof",
    sourcePath: "/media/references/bitpanda-card-proof.gif",
    productVertical: "Finance / card proof",
    fitConfidence: "strong",
    visualTraits: ["physical card", "website in background", "hands holding product"],
    scriptSignals: ["card arrived", "proof of service", "finance product"],
    primaryHookIds: ["proof-first", "tool-demo", "testimonial-flash"],
    secondaryHookIds: ["behind-the-scenes", "b-roll-cut-away"],
    suggestedCategoryIds: ["physical-proof", "finance-card-proof"],
    bestFor: ["finance product credibility", "physical proof", "app-to-card workflow"],
    avoidFor: ["identity quiz", "fashion styling"],
  },
  {
    id: "freedom-card-testimonial",
    title: "Freedom Card Testimonial",
    sourcePath: "/media/references/freedom-card-testimonial.gif",
    productVertical: "Finance / testimonial card",
    fitConfidence: "strong",
    visualTraits: ["creator smiles with card", "brand logo", "white background"],
    scriptSignals: ["testimonial", "card benefit", "personal proof"],
    primaryHookIds: ["testimonial-flash", "proof-first", "face-close-up"],
    secondaryHookIds: ["self-identification", "bold-claim"],
    suggestedCategoryIds: ["card-testimonial", "financial-social-proof"],
    bestFor: ["finance testimonial", "card offer", "human trust signal"],
    avoidFor: ["silent product-only proof", "surreal CGI"],
  },
  {
    id: "airbnb-brand-card",
    title: "Airbnb Brand Card",
    sourcePath: "/media/references/airbnb-brand-card.gif",
    productVertical: "Travel / brand icon card",
    fitConfidence: "gap",
    visualTraits: ["brand color card", "tiny object motion", "minimal set"],
    scriptSignals: ["brand icon", "travel platform signal"],
    primaryHookIds: [],
    secondaryHookIds: ["mystery-object", "text-first"],
    suggestedCategoryIds: ["brand-icon-loop", "minimal-logo-motion"],
    bestFor: ["brand mnemonic", "deck transition", "logo-first creative"],
    avoidFor: ["hook-card media until the actual claim is known"],
  },
  {
    id: "roseskin-definition-card",
    title: "RoseSkin Definition Card",
    sourcePath: "/media/references/roseskin-definition-card.gif",
    productVertical: "Beauty device / definition hook",
    fitConfidence: "strong",
    visualTraits: ["dictionary-style definition", "product use scene", "product thumbnails"],
    scriptSignals: ["definition of lumi-ing", "hair removal", "what are you doing"],
    primaryHookIds: ["text-first", "tool-demo", "self-identification"],
    secondaryHookIds: ["instant-value", "proof-first"],
    suggestedCategoryIds: ["definition-hook", "product-verb"],
    bestFor: ["beauty device education", "coined product verb", "definition-led hook"],
    avoidFor: ["pure product B-roll", "sale urgency"],
  },
  {
    id: "roxa-personality-transformation",
    title: "Roxa Personality Transformation",
    sourcePath: "/media/references/roxa-personality-transformation.gif",
    productVertical: "Beauty / persona transformation",
    fitConfidence: "strong",
    visualTraits: ["creator with sunglasses", "Arabic caption", "personality after service"],
    scriptSignals: ["my personality after", "beauty service transformation", "persona shift"],
    primaryHookIds: ["transformation-before-after", "plot-twist", "self-identification"],
    secondaryHookIds: ["face-close-up", "shock-value"],
    suggestedCategoryIds: ["persona-after-effect", "beauty-service-shift"],
    bestFor: ["post-service transformation", "relatable persona humor", "beauty lifestyle"],
    avoidFor: ["product ingredient proof", "finance card proof"],
  },
  {
    id: "hijab-creator-talk",
    title: "Hijab Creator Talk",
    sourcePath: "/media/references/hijab-creator-talk.gif",
    productVertical: "UGC / creator talk",
    fitConfidence: "gap",
    visualTraits: ["creator talking to camera", "architectural background", "no readable hook in first frame"],
    scriptSignals: ["unknown spoken hook"],
    primaryHookIds: [],
    secondaryHookIds: ["story-open", "face-close-up"],
    suggestedCategoryIds: ["unreviewed-reference", "creator-talk-intake"],
    bestFor: ["manual script review", "UGC intake"],
    avoidFor: ["automatic hook assignment until transcript is known"],
  },
  {
    id: "transit-90m-bold-claim",
    title: "Transit 90M Bold Claim",
    sourcePath: "/media/references/transit-90m-bold-claim.gif",
    productVertical: "Travel logistics / public transport proof",
    fitConfidence: "strong",
    visualTraits: ["creator in transport hub", "large numeric claim", "Arabic overlay", "location context"],
    scriptSignals: ["90 million passengers", "imagine more than", "public scale"],
    primaryHookIds: ["bold-claim", "proof-first", "behind-the-scenes"],
    secondaryHookIds: ["pov-shot", "instant-value"],
    suggestedCategoryIds: ["scale-statistic", "public-logistics-proof"],
    bestFor: ["big-number authority", "travel/public service proof", "infrastructure story"],
    avoidFor: ["product unboxing", "aesthetic product detail"],
  },
  {
    id: "flight-booking-tips",
    title: "Flight Booking Tips",
    sourcePath: "/media/references/flight-booking-tips.gif",
    productVertical: "Travel / booking education",
    fitConfidence: "strong",
    visualTraits: ["creator holds phone", "tips text overlay", "travel booking context"],
    scriptSignals: ["tips for booking the right flight", "how to choose", "travel advice"],
    primaryHookIds: ["instant-value", "step-by-step", "save-this"],
    secondaryHookIds: ["self-identification", "tool-demo"],
    suggestedCategoryIds: ["travel-tips", "booking-advice"],
    bestFor: ["travel education", "saveable tips", "service explainer"],
    avoidFor: ["product packshot", "silent review"],
  },
  {
    id: "coffee-pour-sensory",
    title: "Coffee Pour Sensory",
    sourcePath: "/media/references/coffee-pour-sensory.gif",
    productVertical: "Beverage / sensory pour",
    fitConfidence: "medium",
    visualTraits: ["close-up coffee pour", "foam texture", "lifestyle table setting"],
    scriptSignals: ["sensory product moment", "morning ritual", "texture proof"],
    primaryHookIds: ["b-roll-cut-away", "mystery-object", "proof-first"],
    secondaryHookIds: ["save-this", "instant-value"],
    suggestedCategoryIds: ["sensory-proof", "ritual-moment"],
    bestFor: ["beverage texture", "coffee ritual", "sensory B-roll"],
    avoidFor: ["spoken UGC hook", "urgent offer"],
  },
  {
    id: "delivery-box-reaction",
    title: "Delivery Box Reaction",
    sourcePath: "/media/references/delivery-box-reaction.gif",
    productVertical: "Delivery / unboxing reaction",
    fitConfidence: "medium",
    visualTraits: ["person receives box", "happy reaction", "delivery context"],
    scriptSignals: ["delivery arrived", "surprise unboxing", "reaction moment"],
    primaryHookIds: ["story-open", "mystery-object", "testimonial-flash"],
    secondaryHookIds: ["behind-the-scenes", "cliffhanger-cut"],
    suggestedCategoryIds: ["delivery-reaction", "arrival-moment"],
    bestFor: ["delivery delight", "unboxing reaction", "service arrival"],
    avoidFor: ["polished product-only ad", "statistic hook"],
  },
  {
    id: "hulala-boxing-day-cart",
    title: "Hulala Boxing Day Add to Cart",
    sourcePath: "/media/references/hulala-boxing-day-cart.gif",
    productVertical: "Home furniture / Boxing Day offer",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "Furniture pieces float above an open shipping box with offer text on a clean beige background.",
      firstTextOrAudio: "It's Boxing Day today. Add to Cart.",
      attentionMechanic: "seasonal offer text plus surreal product motion",
      matchingReason: "The opening instantly says why to act today, then uses falling furniture as the visual stop.",
    },
    visualTraits: ["floating chairs", "open box", "Boxing Day text", "add-to-cart prompt"],
    scriptSignals: ["Boxing Day today", "Add to Cart", "seasonal sale"],
    primaryHookIds: ["fear-of-missing-out", "text-first", "visual-pattern-interrupt"],
    secondaryHookIds: ["kinetic-typography", "mystery-object"],
    suggestedCategoryIds: ["timed-sale", "surreal-scale", "commerce-prompt"],
    bestFor: ["holiday sale", "home decor ecommerce", "motion-led offer"],
    avoidFor: ["creator trust proof", "long education"],
  },
  {
    id: "sneaker-seasonal-sale-pile",
    title: "Sneaker Seasonal Sale Pile",
    sourcePath: "/media/references/sneaker-seasonal-sale-pile.gif",
    productVertical: "Footwear / seasonal sale",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A pile of sneakers sits under a clear seasonal-sale headline.",
      firstTextOrAudio: "Seasonal sale. Up to 50% off.",
      attentionMechanic: "offer-first product pile",
      matchingReason: "The hook is the offer clarity: the viewer knows the category, discount, and product range immediately.",
    },
    visualTraits: ["sneaker pile", "seasonal sale headline", "discount text", "clean studio"],
    scriptSignals: ["seasonal sale", "up to 50% off", "product range"],
    primaryHookIds: ["text-first", "fear-of-missing-out", "proof-first"],
    secondaryHookIds: ["b-roll-cut-away", "split-screen-compare"],
    suggestedCategoryIds: ["timed-sale", "product-menu"],
    bestFor: ["footwear sale", "range offer", "retail conversion"],
    avoidFor: ["mystery-led story", "creator testimonial"],
  },
  {
    id: "elan-rituals-cart-drop",
    title: "Elan Rituals Cart Drop",
    sourcePath: "/media/references/elan-rituals-cart-drop.gif",
    productVertical: "Beauty / ecommerce cart motion",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "Beauty bottles float around a wire cart while a cursor points inside it.",
      firstTextOrAudio: "No spoken copy; the cart and cursor imply shopping action.",
      attentionMechanic: "shopping-cart visual metaphor",
      matchingReason: "The first frame uses the cart itself as the hook, making ecommerce intent obvious without needing narration.",
    },
    visualTraits: ["wire cart", "cursor", "floating bottles", "minimal beauty packshots"],
    scriptSignals: ["add to cart", "shop the set", "beauty ritual"],
    primaryHookIds: ["visual-pattern-interrupt", "tool-demo", "text-first"],
    secondaryHookIds: ["mystery-object", "b-roll-cut-away"],
    suggestedCategoryIds: ["commerce-prompt", "cart-metaphor"],
    bestFor: ["beauty ecommerce", "cart reminder", "product range showcase"],
    avoidFor: ["human testimonial", "public-service education"],
  },
  {
    id: "marina-sunset-establishing",
    title: "Marina Sunset Establishing Shot",
    sourcePath: "/media/references/marina-sunset-establishing.gif",
    productVertical: "Destination / cinematic location",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "A cinematic marina view opens at sunset with boats, water, and skyline depth.",
      firstTextOrAudio: "No text; the environment creates the first promise.",
      attentionMechanic: "premium location b-roll",
      matchingReason: "The value is atmosphere and place recognition, so it works best as an establishing hook rather than a product claim.",
    },
    visualTraits: ["marina", "sunset", "skyline", "premium destination"],
    scriptSignals: ["destination reveal", "place mood", "cinematic opening"],
    primaryHookIds: ["b-roll-cut-away", "story-open", "behind-the-scenes"],
    secondaryHookIds: ["proof-first", "pov-shot"],
    suggestedCategoryIds: ["location-reveal", "premium-broll"],
    bestFor: ["destination ads", "venue openings", "luxury lifestyle"],
    avoidFor: ["direct response offer", "text-heavy tutorial"],
  },
  {
    id: "red-silk-texture-open",
    title: "Red Silk Texture Open",
    sourcePath: "/media/references/red-silk-texture-open.gif",
    productVertical: "Fashion / tactile texture",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "A full-frame red silk texture fills the screen before context appears.",
      firstTextOrAudio: "No text; texture is the first hook.",
      attentionMechanic: "macro texture mystery",
      matchingReason: "The first frame asks the viewer to identify the material before the product or message is revealed.",
    },
    visualTraits: ["red silk", "macro texture", "high saturation", "abstract first frame"],
    scriptSignals: ["texture reveal", "material proof", "luxury cue"],
    primaryHookIds: ["mystery-object", "b-roll-cut-away", "proof-first"],
    secondaryHookIds: ["cliffhanger-cut", "text-first"],
    suggestedCategoryIds: ["macro-product-proof", "texture-first"],
    bestFor: ["fashion material stories", "luxury mood", "sensory product proof"],
    avoidFor: ["fast offer ads", "spoken UGC"],
  },
  {
    id: "perfume-drop-creator",
    title: "Perfume Drop Creator",
    sourcePath: "/media/references/perfume-drop-creator.gif",
    productVertical: "Fragrance / creator product drop",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A creator holds a fragrance box toward camera with strong motion blur in the first beat.",
      firstTextOrAudio: "Brand/product moment arrives visually before any caption is needed.",
      attentionMechanic: "product thrust into lens",
      matchingReason: "The motion interrupts the feed and immediately centers the product, with the creator providing trust behind it.",
    },
    visualTraits: ["creator in store", "product held to lens", "motion blur", "fragrance display"],
    scriptSignals: ["product recommendation", "fragrance reveal", "creator demo"],
    primaryHookIds: ["visual-pattern-interrupt", "zoom-in-hook", "proof-first"],
    secondaryHookIds: ["face-close-up", "testimonial-flash"],
    suggestedCategoryIds: ["lens-thrust", "creator-recommendation"],
    bestFor: ["fragrance UGC", "creator product demo", "retail beauty"],
    avoidFor: ["quiet packshot", "step-by-step education"],
  },
  {
    id: "kikikickz-deal-cards",
    title: "Kikikickz Deal Cards",
    sourcePath: "/media/references/kikikickz-deal-cards.gif",
    productVertical: "Footwear / discount cards",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "Discount tape crosses over a stack of branded deal cards.",
      firstTextOrAudio: "Kikikickz Dealz with percentage strips.",
      attentionMechanic: "discount tape pattern interrupt",
      matchingReason: "The first frame is a visual offer stack: brand, deal, and discount language appear together.",
    },
    visualTraits: ["deal cards", "discount tape", "white field", "green offer graphics"],
    scriptSignals: ["dealz", "discount percentages", "sale stack"],
    primaryHookIds: ["fear-of-missing-out", "text-first", "kinetic-typography"],
    secondaryHookIds: ["visual-pattern-interrupt", "countdown-tease"],
    suggestedCategoryIds: ["timed-sale", "offer-proof-stack"],
    bestFor: ["sale campaigns", "footwear deals", "discount reminders"],
    avoidFor: ["premium quiet luxury", "human story hooks"],
  },
  {
    id: "disney-restaurant-point",
    title: "Disney Restaurant Point",
    sourcePath: "/media/references/disney-restaurant-point.gif",
    productVertical: "Entertainment / restaurant moment",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "A man in a restaurant points upward as people sit behind him.",
      firstTextOrAudio: "No readable opening copy; gesture creates the first beat.",
      attentionMechanic: "direct gesture to camera",
      matchingReason: "The raised finger works as a soft stop, but the spoken line should be reviewed before final hook assignment.",
    },
    visualTraits: ["creator pointing", "restaurant setting", "Disney watermark", "group context"],
    scriptSignals: ["recommendation setup", "wait for it", "restaurant context"],
    primaryHookIds: ["before-you-scroll", "story-open", "face-close-up"],
    secondaryHookIds: ["testimonial-flash", "behind-the-scenes"],
    suggestedCategoryIds: ["creator-talk-intake", "place-recommendation"],
    bestFor: ["venue recommendation", "creator story", "experience proof"],
    avoidFor: ["silent product sale", "text-only card"],
  },
  {
    id: "arabic-beauty-opinion-reaction",
    title: "Arabic Beauty Opinion Reaction",
    sourcePath: "/media/references/arabic-beauty-opinion-reaction.gif",
    productVertical: "Beauty / opinion prompt",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "A creator in close-up points to her face with Arabic caption text at the bottom.",
      firstTextOrAudio: "Arabic opinion prompt about her skin/face.",
      attentionMechanic: "face-close opinion question",
      matchingReason: "The first three seconds rely on face proximity and a direct question, making it reviewable as a social-opinion hook.",
    },
    visualTraits: ["creator close-up", "face gesture", "Arabic caption", "beauty reaction"],
    scriptSignals: ["what do you think", "skin/beauty opinion", "question prompt"],
    primaryHookIds: ["face-close-up", "self-identification", "testimonial-flash"],
    secondaryHookIds: ["this-or-that", "proof-first"],
    suggestedCategoryIds: ["opinion-prompt", "localized-commerce"],
    bestFor: ["beauty UGC", "comment prompt", "creator opinion ad"],
    avoidFor: ["silent product packshot", "location reveal"],
  },
  {
    id: "purple-bag-conveyor-hero",
    title: "Purple Bag Conveyor Hero",
    sourcePath: "/media/references/purple-bag-conveyor-hero.gif",
    productVertical: "Fashion accessories / conveyor product scene",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A purple bag and accessories ride through a conveyor tray in an airport-like scene.",
      firstTextOrAudio: "No text; product context is created by the conveyor motion.",
      attentionMechanic: "product in unexpected transit environment",
      matchingReason: "The first frame relocates fashion product into a luggage/security context, creating a visual interruption.",
    },
    visualTraits: ["purple bag", "conveyor belt", "accessories tray", "travel retail metaphor"],
    scriptSignals: ["travel-ready", "bag reveal", "security tray"],
    primaryHookIds: ["b-roll-cut-away", "mystery-object", "visual-pattern-interrupt"],
    secondaryHookIds: ["pov-shot", "proof-first"],
    suggestedCategoryIds: ["location-reveal", "product-in-context"],
    bestFor: ["accessory launches", "travel fashion", "premium product context"],
    avoidFor: ["talking-head education", "finance proof"],
  },
  {
    id: "mini-bag-elevator-scale",
    title: "Mini Bag Elevator Scale",
    sourcePath: "/media/references/mini-bag-elevator-scale.gif",
    productVertical: "Fashion accessories / scale gag",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A tiny handbag sits alone in an elevator, creating a scale joke immediately.",
      firstTextOrAudio: "No text; the size mismatch carries the hook.",
      attentionMechanic: "tiny product in oversized environment",
      matchingReason: "The first second is a visual puzzle: why is the bag alone and so small in this large elevator scene?",
    },
    visualTraits: ["tiny handbag", "elevator", "scale contrast", "empty environment"],
    scriptSignals: ["scale gag", "mini bag", "unexpected placement"],
    primaryHookIds: ["visual-pattern-interrupt", "mystery-object", "expectations-subvert"],
    secondaryHookIds: ["shock-value", "proof-first"],
    suggestedCategoryIds: ["surreal-scale", "product-in-context"],
    bestFor: ["fashion accessory tease", "scale humor", "premium product reveal"],
    avoidFor: ["literal how-to content", "discount offer cards"],
  },
  {
    id: "luxury-car-giant-face",
    title: "Luxury Car Giant Face Composite",
    sourcePath: "/media/references/luxury-car-giant-face.gif",
    productVertical: "Luxury lifestyle / surreal composite",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A giant face with sunglasses looms behind a luxury car and a tiny full-body figure.",
      firstTextOrAudio: "No text; the surreal composite is the hook.",
      attentionMechanic: "impossible scale luxury scene",
      matchingReason: "The first frame breaks realism immediately, which makes it a strong visual-pattern interrupt.",
    },
    visualTraits: ["giant face", "luxury car", "sunglasses", "surreal scale"],
    scriptSignals: ["luxury persona", "impossible scene", "style flex"],
    primaryHookIds: ["visual-pattern-interrupt", "shock-value", "mystery-object"],
    secondaryHookIds: ["pov-shot", "proof-first"],
    suggestedCategoryIds: ["surreal-scale", "persona-after-effect"],
    bestFor: ["luxury fashion", "automotive/lifestyle", "surreal visual hook"],
    avoidFor: ["calm utility education", "official announcements"],
  },
  {
    id: "special-shoes-detail",
    title: "Special Shoes Detail",
    sourcePath: "/media/references/special-shoes-detail.gif",
    productVertical: "Footwear / product detail text",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "Cream shoes fill the frame with a bold vertical text block beginning to animate.",
      firstTextOrAudio: "Special.",
      attentionMechanic: "macro product plus typographic label",
      matchingReason: "The product appears before context, while the label tells the viewer how to interpret it.",
    },
    visualTraits: ["shoe close-up", "soft focus", "vertical typography", "cream product detail"],
    scriptSignals: ["special", "product label", "premium footwear"],
    primaryHookIds: ["b-roll-cut-away", "text-first", "mystery-object"],
    secondaryHookIds: ["proof-first", "kinetic-typography"],
    suggestedCategoryIds: ["macro-product-proof", "detail-first"],
    bestFor: ["footwear product detail", "fashion sale creative", "premium product reveal"],
    avoidFor: ["creator confession", "strong statistic claims"],
  },
  {
    id: "morning-routine-alarm",
    title: "Morning Routine Alarm",
    sourcePath: "/media/references/morning-routine-alarm.gif",
    productVertical: "Lifestyle / morning routine",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A phone alarm sits on bedding with Arabic text over the screen.",
      firstTextOrAudio: "Morning routine text in Arabic.",
      attentionMechanic: "routine cue from a familiar alarm screen",
      matchingReason: "The alarm is a universal first-second signal, and the text clarifies the routine promise.",
    },
    visualTraits: ["phone alarm", "bed sheets", "Arabic overlay", "morning routine"],
    scriptSignals: ["morning routine", "wake-up ritual", "routine setup"],
    primaryHookIds: ["text-first", "story-open", "step-by-step"],
    secondaryHookIds: ["save-this", "instant-value"],
    suggestedCategoryIds: ["routine-cue", "timely-ritual"],
    bestFor: ["routine content", "beauty/wellness rituals", "saveable lifestyle tips"],
    avoidFor: ["hard sale", "product-only proof"],
  },
  {
    id: "creator-phone-quiet-ugc",
    title: "Creator Phone Quiet UGC",
    sourcePath: "/media/references/creator-phone-quiet-ugc.gif",
    productVertical: "UGC / phone moment",
    fitConfidence: "gap",
    firstThreeSeconds: {
      firstFrame: "A creator sits with a phone in a casual home setting.",
      firstTextOrAudio: "No visible hook text; spoken line needs review.",
      attentionMechanic: "quiet creator setup",
      matchingReason: "The visual alone is not enough to assign a precise hook until the spoken first line is known.",
    },
    visualTraits: ["creator seated", "phone in hand", "home setting", "quiet UGC"],
    scriptSignals: ["unknown spoken hook", "phone moment"],
    primaryHookIds: [],
    secondaryHookIds: ["story-open", "face-close-up", "tool-demo"],
    suggestedCategoryIds: ["unreviewed-reference", "creator-talk-intake"],
    bestFor: ["manual transcript review", "UGC intake", "phone app demos"],
    avoidFor: ["automatic hook assignment"],
  },
  {
    id: "starbucks-menu-pov",
    title: "Starbucks Menu POV",
    sourcePath: "/media/references/starbucks-menu-pov.gif",
    productVertical: "Food retail / menu decision",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "A customer looks at an in-store Starbucks menu from a POV angle.",
      firstTextOrAudio: "No opening text; the menu decision creates the first beat.",
      attentionMechanic: "in-store POV choice setup",
      matchingReason: "The hook comes from being physically inside the buying moment and waiting for the choice/reveal.",
    },
    visualTraits: ["store counter", "menu board", "customer POV", "food retail"],
    scriptSignals: ["what should I order", "menu decision", "new drink"],
    primaryHookIds: ["pov-shot", "this-or-that", "mystery-object"],
    secondaryHookIds: ["instant-value", "story-open"],
    suggestedCategoryIds: ["choice-game", "retail-decision"],
    bestFor: ["menu recommendation", "food retail POV", "choice prompt"],
    avoidFor: ["product packshot", "finance proof"],
  },
  {
    id: "saco-app-pov",
    title: "SACO App POV",
    sourcePath: "/media/references/saco-app-pov.gif",
    productVertical: "Home retail / app demo",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "Hands open a SACO app on a phone in front of a couch.",
      firstTextOrAudio: "SACO logo appears on the phone.",
      attentionMechanic: "app-open proof in product context",
      matchingReason: "The scene instantly connects the app to the home product category, making it useful as a tool/demo hook.",
    },
    visualTraits: ["phone app", "SACO logo", "couch background", "hands-on demo"],
    scriptSignals: ["open the app", "shop from home", "app proof"],
    primaryHookIds: ["tool-demo", "pov-shot", "proof-first"],
    secondaryHookIds: ["instant-value", "step-by-step"],
    suggestedCategoryIds: ["app-open-proof", "ecommerce-proof"],
    bestFor: ["retail app demo", "home shopping", "tool proof"],
    avoidFor: ["brand-only awareness", "pure lifestyle B-roll"],
  },
  {
    id: "all-item-sale-fashion-grid",
    title: "All Item Sale Fashion Grid",
    sourcePath: "/media/references/all-item-sale-fashion-grid.gif",
    productVertical: "Fashion / sale collage",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A fashion collage announces an all-item sale up to 50% off.",
      firstTextOrAudio: "All item sale. Up to 50% off.",
      attentionMechanic: "collage plus discount headline",
      matchingReason: "The opening is clear and immediate: fashion, sale, discount, and multiple looks all arrive at once.",
    },
    visualTraits: ["fashion collage", "sale typography", "multiple looks", "discount offer"],
    scriptSignals: ["all item sale", "up to 50% off", "collection sale"],
    primaryHookIds: ["text-first", "fear-of-missing-out", "split-screen-compare"],
    secondaryHookIds: ["b-roll-cut-away", "countdown-tease"],
    suggestedCategoryIds: ["timed-sale", "range-grid"],
    bestFor: ["fashion sale", "collection promo", "Snap commerce"],
    avoidFor: ["subtle brand film", "spoken tutorial"],
  },
  {
    id: "streaming-omg-reaction",
    title: "Streaming OMG Reaction",
    sourcePath: "/media/references/streaming-omg-reaction.gif",
    productVertical: "Streaming / reaction teaser",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A red-lit close-up face fills the screen with a large OMG caption.",
      firstTextOrAudio: "OMG!",
      attentionMechanic: "giant reaction text over face-close-up",
      matchingReason: "The opening gives emotion before context, which is ideal for streaming or entertainment curiosity.",
    },
    visualTraits: ["face close-up", "red lighting", "OMG text", "streaming logos"],
    scriptSignals: ["OMG", "reaction", "entertainment tease"],
    primaryHookIds: ["shock-value", "face-close-up", "text-first"],
    secondaryHookIds: ["curiosity-gap", "plot-twist"],
    suggestedCategoryIds: ["reaction-tease", "streaming-title-card"],
    bestFor: ["streaming teasers", "entertainment reaction", "plot surprise"],
    avoidFor: ["retail product proof", "calm education"],
  },
  {
    id: "scream-tara-door-open",
    title: "Scream Tara Door Open",
    sourcePath: "/media/references/scream-tara-door-open.gif",
    productVertical: "Streaming / character cold open",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "A character peeks from a trailer door with a name label on the door.",
      firstTextOrAudio: "Scream / Tara visual cue.",
      attentionMechanic: "character enters mid-scene",
      matchingReason: "The hook is story context: the viewer is dropped into a scene and waits to see what happens next.",
    },
    visualTraits: ["character reveal", "door frame", "title cue", "behind-the-scenes feel"],
    scriptSignals: ["character introduction", "scene tease", "horror title"],
    primaryHookIds: ["story-open", "cliffhanger-cut", "mystery-object"],
    secondaryHookIds: ["text-first", "plot-twist"],
    suggestedCategoryIds: ["character-cold-open", "streaming-title-card"],
    bestFor: ["entertainment teasers", "character reveal", "scene cold open"],
    avoidFor: ["commerce offer", "product tutorial"],
  },
  {
    id: "empty-basket-grocery",
    title: "Empty Basket Grocery",
    sourcePath: "/media/references/empty-basket-grocery.gif",
    productVertical: "Grocery / basket setup",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "An empty grocery basket is framed overhead with fresh produce around it.",
      firstTextOrAudio: "No text; the empty basket sets up a fill/reveal.",
      attentionMechanic: "empty object invites completion",
      matchingReason: "The first frame creates a clear gap: the basket needs to be filled, so the viewer anticipates the next items.",
    },
    visualTraits: ["empty basket", "overhead shot", "fresh produce", "grocery context"],
    scriptSignals: ["shopping list", "fill the basket", "recipe setup"],
    primaryHookIds: ["curiosity-gap", "mystery-object", "step-by-step"],
    secondaryHookIds: ["instant-value", "save-this"],
    suggestedCategoryIds: ["commerce-prompt", "recipe-setup"],
    bestFor: ["grocery list", "meal prep", "retail basket build"],
    avoidFor: ["luxury fashion", "creator testimonial"],
  },
  {
    id: "defender-desert-snap",
    title: "Defender Desert Snap",
    sourcePath: "/media/references/defender-desert-snap.gif",
    productVertical: "Automotive / desert lifestyle",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "A Defender sits in a desert scene with a Snap-style ad frame.",
      firstTextOrAudio: "Brand/ad frame with desert setting.",
      attentionMechanic: "aspirational vehicle location",
      matchingReason: "The first beat sells a destination mood and product identity rather than a script claim.",
    },
    visualTraits: ["SUV", "desert", "Snap ad UI", "crescent sky"],
    scriptSignals: ["ad frame", "explore", "outdoor vehicle"],
    primaryHookIds: ["b-roll-cut-away", "proof-first", "story-open"],
    secondaryHookIds: ["pov-shot", "mystery-object"],
    suggestedCategoryIds: ["location-reveal", "premium-broll"],
    bestFor: ["automotive lifestyle", "outdoor destination", "brand awareness"],
    avoidFor: ["discount-led retail", "app demo"],
  },
  {
    id: "daddys-home-halloween-title",
    title: "Daddy's Home Halloween Title",
    sourcePath: "/media/references/daddys-home-halloween-title.gif",
    productVertical: "Streaming / seasonal title card",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "A bold Halloween title card introduces Daddy's Home 2 with the actor centered.",
      firstTextOrAudio: "Halloween Dadvice. Daddy's Home 2.",
      attentionMechanic: "seasonal title takeover",
      matchingReason: "The title card makes the seasonal angle and content title impossible to miss in the first second.",
    },
    visualTraits: ["orange title card", "actor centered", "Halloween text", "streaming promo"],
    scriptSignals: ["Halloween", "title announcement", "movie promo"],
    primaryHookIds: ["text-first", "fear-of-missing-out", "story-open"],
    secondaryHookIds: ["bold-claim", "plot-twist"],
    suggestedCategoryIds: ["streaming-title-card", "cultural-moment-advice"],
    bestFor: ["seasonal streaming promo", "title recall", "entertainment ads"],
    avoidFor: ["product feature proof", "UGC tutorial"],
  },
  {
    id: "health-nag-collagen-jar",
    title: "Health Nag Collagen Jar",
    sourcePath: "/media/references/health-nag-collagen-jar.gif",
    productVertical: "Health supplement / product proof",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A collagen jar rotates in a Snap-style product ad frame.",
      firstTextOrAudio: "Not your Ordinary Collagen.",
      attentionMechanic: "claim-led pack close-up",
      matchingReason: "The phrase creates a contrast claim while the product is immediately visible.",
    },
    visualTraits: ["collagen jar", "ad frame", "top-down product", "benefit ring text"],
    scriptSignals: ["not your ordinary collagen", "health benefit", "product proof"],
    primaryHookIds: ["bold-claim", "proof-first", "mystery-object"],
    secondaryHookIds: ["text-first", "b-roll-cut-away"],
    suggestedCategoryIds: ["pack-claim", "certification-proof"],
    bestFor: ["supplement ads", "claim-led CPG", "Snap product proof"],
    avoidFor: ["fashion styling", "story-only content"],
  },
  {
    id: "petra-movie-ending-question",
    title: "Petra Movie Ending Question",
    sourcePath: "/media/references/petra-movie-ending-question.gif",
    productVertical: "Travel entertainment / question prompt",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A creator stands in a dramatic travel location with bilingual subtitles asking a question.",
      firstTextOrAudio: "How does the movie end?",
      attentionMechanic: "question hook in cinematic location",
      matchingReason: "The opening question creates a curiosity loop, while the setting gives the story visual stakes.",
    },
    visualTraits: ["creator on location", "bilingual subtitle", "Petra backdrop", "question prompt"],
    scriptSignals: ["How does the movie end", "question", "story tease"],
    primaryHookIds: ["curiosity-gap", "story-open", "self-identification"],
    secondaryHookIds: ["plot-twist", "text-first"],
    suggestedCategoryIds: ["question-prompt", "location-reveal"],
    bestFor: ["travel story", "entertainment education", "question-led hook"],
    avoidFor: ["product packshot", "discount offer"],
  },
  {
    id: "cafe-storefront-walk-in",
    title: "Cafe Storefront Walk-In",
    sourcePath: "/media/references/cafe-storefront-walk-in.gif",
    productVertical: "Hospitality / location reveal",
    fitConfidence: "medium",
    firstThreeSeconds: {
      firstFrame: "A cafe storefront is shown from outside before the viewer enters the space.",
      firstTextOrAudio: "No opening text; the storefront acts as the reveal.",
      attentionMechanic: "walk-in location preview",
      matchingReason: "The first beat invites the viewer into a physical place, useful for venue discovery.",
    },
    visualTraits: ["cafe exterior", "glass storefront", "walk-in perspective", "venue reveal"],
    scriptSignals: ["come with me", "new spot", "inside reveal"],
    primaryHookIds: ["pov-shot", "b-roll-cut-away", "behind-the-scenes"],
    secondaryHookIds: ["story-open", "mystery-object"],
    suggestedCategoryIds: ["location-reveal", "place-recommendation"],
    bestFor: ["restaurant/cafe discovery", "venue ads", "experience reveal"],
    avoidFor: ["text-first offers", "finance proof"],
  },
  {
    id: "iftar-tabletop-serving",
    title: "Iftar Tabletop Serving",
    sourcePath: "/media/references/iftar-tabletop-serving.gif",
    productVertical: "Food / Ramadan table moment",
    fitConfidence: "strong",
    firstThreeSeconds: {
      firstFrame: "A hand serves food on a Ramadan-style tabletop with Arabic text overlay.",
      firstTextOrAudio: "Arabic food/iftar-style caption.",
      attentionMechanic: "seasonal meal ritual close-up",
      matchingReason: "The opening ties food, ritual, and a clear cultural moment together, making it strong for saveable food content.",
    },
    visualTraits: ["food serving", "Ramadan table", "Arabic overlay", "close-up meal"],
    scriptSignals: ["iftar", "table serving", "meal ritual"],
    primaryHookIds: ["step-by-step", "save-this", "b-roll-cut-away"],
    secondaryHookIds: ["instant-value", "story-open"],
    suggestedCategoryIds: ["cultural-moment-advice", "meal-timing-split"],
    bestFor: ["Ramadan food", "recipe or serving idea", "seasonal hospitality"],
    avoidFor: ["fashion sale", "app demo"],
  },
];

export const hookGapSuggestions: HookGapSuggestion[] = [
  {
    id: "digital-double",
    proposedCategory: "Persona & Identity",
    proposedHookName: "The Digital Twin",
    pattern: "Interrupt",
    intent: "Contrast",
    whenToCreate: "Use when a creator, avatar, AI clone, Bitmoji, or character version of the buyer is the main visual idea.",
    exampleLine: "I accidentally dressed exactly like my avatar.",
    mediaSignals: ["avatar beside creator", "AI/persona duplicate", "matching outfit", "identity play"],
  },
  {
    id: "occasion-fit",
    proposedCategory: "Occasion Styling",
    proposedHookName: "The Occasion Fit",
    pattern: "Clarify",
    intent: "Education",
    whenToCreate: "Use when the strongest reason to watch is an event, vibe, or social situation rather than a product claim.",
    exampleLine: "The shoes I would wear for date night, brunch, and the after-party.",
    mediaSignals: ["date night", "festival", "airport fit", "wedding guest", "office look"],
  },
  {
    id: "two-pick-edit",
    proposedCategory: "Commerce Picks",
    proposedHookName: "The Two-Pick Edit",
    pattern: "Clarify",
    intent: "Education",
    whenToCreate: "Use when a product video is primarily a curated edit, shortlist, or shopping recommendation.",
    exampleLine: "The only two boots I would pack for a weekend trip.",
    mediaSignals: ["two products held up", "ranked picks", "editor's choice", "shopping shortlist"],
  },
  {
    id: "trend-forecast",
    proposedCategory: "Trend Forecast",
    proposedHookName: "The Forecast Call",
    pattern: "Intrigue",
    intent: "Authority",
    whenToCreate: "Use when the creator frames the product as a trend prediction or next-season signal.",
    exampleLine: "POV: these are the boots everyone asks about next month.",
    mediaSignals: ["forecast text", "next trend", "season prediction", "what's coming"],
  },
  {
    id: "closet-reset",
    proposedCategory: "Wardrobe Refresh",
    proposedHookName: "The Closet Reset",
    pattern: "Interrupt",
    intent: "Urgency",
    whenToCreate: "Use when the media pushes a refresh, swap, cleanout, capsule, or seasonal update action.",
    exampleLine: "It is time to retire the old pair and update your closet.",
    mediaSignals: ["closet update", "wardrobe refresh", "seasonal reset", "replace this with that"],
  },
  {
    id: "box-reveal",
    proposedCategory: "Product Reveal",
    proposedHookName: "The Box Reveal",
    pattern: "Reward",
    intent: "Curiosity",
    whenToCreate: "Use when the product is hidden inside packaging and the suspense comes from opening or previewing it.",
    exampleLine: "I already know what is inside this box, and it is about to sell out.",
    mediaSignals: ["shoe box", "package close-up", "unboxing", "hands opening product"],
  },
  {
    id: "cultural-moment-advice",
    proposedCategory: "Cultural Moment",
    proposedHookName: "The Timely Ritual",
    pattern: "Clarify",
    intent: "Education",
    whenToCreate: "Use when advice is valuable because it is tied to a calendar moment, cultural season, holiday, or shared ritual.",
    exampleLine: "Three things to change in your routine during Ramadan.",
    mediaSignals: ["Ramadan", "holiday routine", "seasonal advice", "shared ritual"],
  },
  {
    id: "meal-timing-split",
    proposedCategory: "Food Timing",
    proposedHookName: "The Meal Moment Split",
    pattern: "Clarify",
    intent: "Education",
    whenToCreate: "Use when food content is framed around when to eat it, not just how to make it.",
    exampleLine: "This salad works for iftar and suhoor for two different reasons.",
    mediaSignals: ["iftar", "suhoor", "breakfast vs dinner", "pre-workout vs post-workout"],
  },
  {
    id: "choice-game",
    proposedCategory: "Interactive Choice",
    proposedHookName: "The Which One Are You",
    pattern: "Intrigue",
    intent: "Contrast",
    whenToCreate: "Use when the viewer is asked to pick an identity, flavor, style, or side before the reveal.",
    exampleLine: "Which one are you: sour, sweet, or chaotic?",
    mediaSignals: ["which one are you", "pick one", "comment your choice", "identity quiz"],
  },
  {
    id: "silent-review",
    proposedCategory: "Reaction Review",
    proposedHookName: "The Silent Review",
    pattern: "Reward",
    intent: "Authority",
    whenToCreate: "Use when facial reaction, gestures, or edit rhythm do the reviewing without spoken explanation.",
    exampleLine: "Silent review: wait for the third bite.",
    mediaSignals: ["silent review", "reaction only", "no talking", "facial score"],
  },
  {
    id: "product-persona",
    proposedCategory: "Product Character",
    proposedHookName: "The Product Persona",
    pattern: "Interrupt",
    intent: "Curiosity",
    whenToCreate: "Use when the product itself becomes a character through face animation, voiceover, or surreal motion.",
    exampleLine: "What this candy would say if it could talk.",
    mediaSignals: ["animated face", "talking product", "package personality", "object character"],
  },
  {
    id: "use-case-unboxing",
    proposedCategory: "Use-Case Unboxing",
    proposedHookName: "The Room Setup Reveal",
    pattern: "Reward",
    intent: "Story",
    whenToCreate: "Use when unboxing is not the whole hook; the real hook is the room, routine, or life moment the product enters.",
    exampleLine: "Unboxing everything we needed for the nursery corner.",
    mediaSignals: ["nursery setup", "room reset", "lifestyle unboxing", "product in context"],
  },
  {
    id: "forced-perspective",
    proposedCategory: "Perspective Trick",
    proposedHookName: "The Forced Perspective",
    pattern: "Interrupt",
    intent: "Curiosity",
    whenToCreate: "Use when the first second is a visual illusion created by hand placement, scale, distance, or camera angle.",
    exampleLine: "Tiny market, giant appetite.",
    mediaSignals: ["pinch gesture", "scale illusion", "POV hand", "forced perspective"],
  },
  {
    id: "collab-reveal",
    proposedCategory: "Collaboration Reveal",
    proposedHookName: "The Collab Signal",
    pattern: "Clarify",
    intent: "Authority",
    whenToCreate: "Use when the strongest hook is two brands, creators, or worlds coming together.",
    exampleLine: "This is what happens when performance sneakers meet luxury design.",
    mediaSignals: ["brand x brand", "collab logo", "drop tease", "limited edition"],
  },
  {
    id: "macro-product-proof",
    proposedCategory: "Macro Product Proof",
    proposedHookName: "The Detail Proof",
    pattern: "Reward",
    intent: "Authority",
    whenToCreate: "Use when close-up material, texture, build, or movement proves quality before any claim is made.",
    exampleLine: "The sole is the reason these do not look like every other white sneaker.",
    mediaSignals: ["macro detail", "material close-up", "sole movement", "texture proof"],
  },
  {
    id: "ar-overlay-reveal",
    proposedCategory: "Digital Overlay",
    proposedHookName: "The AR Reveal",
    pattern: "Interrupt",
    intent: "Curiosity",
    whenToCreate: "Use when a phone, overlay, or generated layer changes what the viewer sees in the real scene.",
    exampleLine: "Point the camera at the box and the shoe appears.",
    mediaSignals: ["phone overlay", "AR reveal", "digital layer", "mixed reality"],
  },
  {
    id: "surreal-scale",
    proposedCategory: "Surreal Scale",
    proposedHookName: "The Giant Object",
    pattern: "Interrupt",
    intent: "Urgency",
    whenToCreate: "Use when impossible scale, CGI outdoor objects, or oversized products are the attention device.",
    exampleLine: "They did not launch a billboard. They launched the box.",
    mediaSignals: ["giant object", "CGI OOH", "floating product", "impossible scale"],
  },
  {
    id: "unreviewed-reference",
    proposedCategory: "Needs Review",
    proposedHookName: "Unclassified Reference",
    pattern: "Intrigue",
    intent: "Curiosity",
    whenToCreate: "Use only as an intake bucket until the first frame, script, and payoff are reviewed.",
    exampleLine: "Do not assign this until the media is reviewed.",
    mediaSignals: ["unknown content", "filename only", "needs visual pass"],
  },
];

function linkedExamples(seed: HookSeed, index: number): VerticalExample[] {
  const chosen = [verticalProfiles[index % 10], verticalProfiles[(index + 3) % 10], verticalProfiles[(index + 7) % 10]];
  return chosen.map((vertical, offset) => ({
    verticalId: vertical.id,
    verticalName: vertical.name,
    verticalColor: vertical.color,
    script: `${seed.example.replace(/\.$/, "")} for ${vertical.name.toLowerCase()}.`,
    visualDirection: `${vertical.prompt}; ${offset === 0 ? "open tight and reveal context" : "cut quickly between proof and reaction"}.`,
    format: offset === 1 ? "studio" : offset === 2 ? "screen" : "ugc",
  }));
}

export const hooks: Hook[] = hookSeeds.map((seed, index) => ({
  ...seed,
  categoryLabel: categoryMeta[seed.category].label,
  caption: seed.example,
  whatItIs: seed.description,
  whenToUse: [
    `Use when the viewer already cares about ${categoryMeta[seed.category].label.toLowerCase()}.`,
    "Use when the payoff can arrive within the next 5 to 12 seconds.",
    "Use when the first frame can clearly support the promise.",
  ],
  whenNotToUse: [
    "Avoid when the claim is generic or cannot be proven.",
    "Avoid when the setup takes longer than the payoff.",
    "Avoid repeating the same structure across every post.",
  ],
  shootingSteps: [
    "Open on the strongest frame or line.",
    "Hold the first beat long enough to register.",
    "Move quickly into proof, context, or payoff.",
  ],
  variations: [
    { name: "Direct Line", description: `Say the simplest version of: ${seed.example}` },
    { name: "Visual First", description: `Show the proof visually before naming ${seed.displayName}.` },
    { name: "Soft Sell", description: "Keep the same structure but lower the intensity for warmer audiences." },
  ],
  related: hookSeeds
    .filter((other) => other.id !== seed.id && (other.pattern === seed.pattern || other.category === seed.category))
    .slice(0, 4)
    .map((other) => other.id),
  tags: Array.from(new Set([
    seed.pattern.toLowerCase(),
    seed.category.toLowerCase(),
    seed.subcategory.toLowerCase().replace(/\s+/g, "-"),
    seed.intent.toLowerCase(),
    seed.productionTier.toLowerCase(),
  ])),
  effectiveness: seed.featured ? 5 : index < 18 ? 5 : index < 36 ? 4 : 3,
  funnelFit: index % 5 === 0 ? ["TOF", "MOF"] : index % 3 === 0 ? ["MOF", "BOF"] : ["TOF"],
  mediaTier: "placeholder",
  palette: palettes[index % palettes.length],
  verticalExamples: linkedExamples(seed, index),
}));

const unassignedIds = new Set([1, 3, 5, 21, 26, 27, 32, 40, 44]);
const inspirationTags = ["ugc", "reel", "local", "creator", "demo", "caption", "reaction", "proof", "story", "voice"];

export const inspirationVideos: InspirationVideo[] = Array.from({ length: Math.max(47, mediaHookMatrix.length) }, (_, index) => {
  const number = index + 1;
  const matrixItem = mediaHookMatrix[index];
  if (matrixItem) {
    const assignedHookId = matrixItem.primaryHookIds[0];
    const assignedHook = hooks.find((hook) => hook.id === assignedHookId);
    const canAssign = matrixItem.fitConfidence !== "gap" && Boolean(assignedHook);
    return {
      id: `vid_${String(number).padStart(3, "0")}`,
      title: matrixItem.title,
      tags: [matrixItem.fitConfidence, matrixItem.productVertical.split("/")[0].trim().toLowerCase()],
      status: canAssign ? "promoted" : "unassigned",
      assignedHookId: canAssign ? assignedHookId : undefined,
      matchId: matrixItem.id,
      videoUrl: matrixItem.sourcePath,
      palette: palettes[(index + 2) % palettes.length],
    };
  }
  const hook = hooks[index % hooks.length];
  const promoted = !unassignedIds.has(number);
  return {
    id: `vid_${String(number).padStart(3, "0")}`,
    title: promoted ? `${hook.displayName} reference` : `Unassigned spark ${number}`,
    tags: [inspirationTags[index % inspirationTags.length], inspirationTags[(index + 4) % inspirationTags.length]],
    status: promoted ? "promoted" : "unassigned",
    assignedHookId: promoted ? hook.id : undefined,
    videoUrl: `${referenceMedia[(index + 3) % referenceMedia.length].videoUrl}#t=${(index % 7) * 1.2}`,
    palette: palettes[(index + 2) % palettes.length],
  };
});

export const intentLabels: Intent[] = ["Curiosity", "Authority", "Story", "Urgency", "Education", "Contrast", "Exclusive"];
export const productionTiers: ProductionTier[] = ["UGC", "Studio", "AI", "Found"];
